mongodb_enquete/config/routes.rb
MongodbEnquete::Application.routes.draw do
  resources :answers do
    collection do
      get 'list'
    end
  end

  resources :questions

  resources :enquetes do
    collection do
      get 'create_default'
    end
  end

end

mongodb_enquete/app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps
  field :user_id, type: Integer
  field :enquete_id, type: String
  validates_presence_of :user_id, :enquete_id
end

mongodb_enquete/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/list
  # GET /answers/list.json
  def list
    @answers = Answer.all
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @enquete = Enquete.find(params[:enquete_id])
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    if params[:commit]
      questions = Enquete.find(params[:answer][:enquete_id]).questions
      @err_msg = {}

      questions.each do |q|
        if q.required_column && params[:answer][q.question_number].blank?
          @err_msg[q.question_number] = "入力されていません"
        end
      end

      if @err_msg.blank?
        answer = Answer.new(params[:answer])
        answer.save!
        flash[:msg] = "回答を受け付けました"
        redirect_to action: 'show', controller: 'enquetes', id: params[:answer][:enquete_id]
      else
        @enquete = Enquete.find(params[:answer][:enquete_id])
        render action: 'show'
      end
    end
  end

  # POST /answers
  # POST /answers.json
  def create_test
    2.times do
      condition = {}
      (1..12).each do |n|
        type = rand(100) % 4
        if type == 1
          condition["q_#{n}"] = "a_#{n}"
        elsif type == 2
          condition["q_#{n}"] = "a\nb_#{n}"
        elsif type == 3
          condition["q_#{n}"] = 1 + rand(5)
        else
          list = [1, 2, 3, 4, 5]
          condition["q_#{n}"] = list.sort_by{rand}[0..rand(5)]
        end
      end

      answer = Answer.new(
          condition.merge(
            user_id: 1,
            enquete_id: 1
          )
      )
      answer[:q_13] = 11
      answer[:q_14] = "test"
      answer.save!
    end

    render test: "completed"
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

mongodb_enquete/app/helpers/answers_helper.rb
module AnswersHelper
end

mongodb_enquete/app/views/answers/_form.html.erb
<%= form_for(@answer, url: {action: 'create'}) do |f| %>
  <% @enquete.questions.sort{|a,b| a.question_number.split(/_/)[1].to_i <=> b.question_number.split(/_/)[1].to_i}.each do |q| %>
    <% @answer[q.question_number] = nil %>
    <% n = q.question_number.split(/_/)[1].to_i %>
    <div class="header">質問<%= n %></div>
    <div class="question">
      <% if @err_msg && @err_msg[q.question_number] %>
        <span class="err_msg"><%= @err_msg[q.question_number] %></span>
      <% end %>
      <div class="title"><%= q.body %> <%= %Q!<span class="requires">※必須</span>! if q.required_column %></div>
      <% if q.type == 'text' %>
        <%= f.text_field q.question_number %>
      <% elsif q.type == 'radio' %>
        <% q.choices.each_with_index do |choice, i| %>
          <%= check_box_tag "answer[#{q.question_number}][]", i, false, id: "answer_#{q.question_number}_#{i}" %>
          <label for="answer_<%= q.question_number %>_<%= i %>"><%= choice %></label><br />
        <% end %>
      <% elsif q.type == 'checkbox' %>
        <% q.choices.each_with_index do |choice, i| %>
          <%= f.radio_button q.question_number, i %>
          <label for="answer_<%= q.question_number %>_<%= i %>"><%= choice %></label><br />
        <% end %>
      <% elsif q.type == 'pulldown' %>
        <%
          list = []
          q.choices.each_with_index do |choice, i|
            list << [choice, i]
          end
        %>
        <%= f.select q.question_number, list %>
      <% elsif q.type == 'textarea' %>
        <%= f.text_area q.question_number, size: '40x5' %>
      <% end %>
    </div>
    <div class="clear"></div>
  <% end %>
  <%= f.hidden_field :user_id, value: 1 %>
  <%= f.hidden_field :enquete_id, value: @enquete.id %>
  <div><%= f.submit 'この内容で送信する' %></div>
<% end %>

mongodb_enquete/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

mongodb_enquete/app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>User</th>
    <th>Enquete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.user_id %></td>
    <td><%= answer.enquete_id %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

mongodb_enquete/app/views/answers/list.html.erb
<style>
  table {
    border: 1px solid black;
    border-spacing: 0px;
    border-collapse: collapse;
  }
  table th {
    background-color: silver;
  }
  table th, td {
    border: 1px solid black;
    padding: 2px;
  }
</style>

<table>
  <% @answers.each_with_index do |answer, i| %>
    <% _keys = answer.attributes.keys.select{|k| k =~ /^q/}.sort{|a, b| a.split(/_/)[1].to_i <=> b.split(/_/)[1].to_i} %>
    <% if i.zero? %>
      <tr>
        <% _keys.each do |key| %>
          <th><%= key %></th>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <% _keys.each do |key| %>
        <td>
          <% if answer[key].instance_of?(Array) %>
            <%= answer[key].join(', ') %>
          <% else %>
            <% if answer[key].instance_of?(String) %>
              <%= answer[key].gsub("\n", "<br />") %>
            <% else %>
              <%= answer[key] %>
            <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

mongodb_enquete/app/views/answers/new.html.erb
<h2><%= link_to "アンケートサンプル", {action: 'index'}, {style: "text-decoration: none"} %></h2>

<p id="notice"><%= notice %></p>

<div class="enquete_title"><%= @enquete.name %></div>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

mongodb_enquete/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @answer.user_id %>
</p>

<p>
  <b>Enquete:</b>
  <%= @answer.enquete_id %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>