mongodb_enquete/config/routes.rb
MongodbEnquete::Application.routes.draw do
  resources :answers do
    collection do
      get 'list'
    end
  end

  resources :questions

  resources :enquetes do
    collection do
      get 'create_default'
    end
  end

end

mongodb_enquete/app/models/enquete.rb
class Enquete
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  embeds_many :questions
  validates_presence_of :name
end

mongodb_enquete/app/controllers/enquetes_controller.rb
class EnquetesController < ApplicationController
  # GET /enquetes
  # GET /enquetes.json
  def index
    @enquetes = Enquete.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enquetes }
    end
  end

  # GET /enquetes/1
  # GET /enquetes/1.json
  def show
    @enquete = Enquete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enquete }
    end
  end

  # GET /enquetes/new
  # GET /enquetes/new.json
  def new
    @enquete = Enquete.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enquete }
    end
  end

  # GET /enquetes/1/edit
  def edit
    @enquete = Enquete.find(params[:id])
  end

  # POST /enquetes
  # POST /enquetes.json
  def create
    @enquete = Enquete.new(params[:enquete])

    respond_to do |format|
      if @enquete.save
        format.html { redirect_to @enquete, notice: 'Enquete was successfully created.' }
        format.json { render json: @enquete, status: :created, location: @enquete }
      else
        format.html { render action: "new" }
        format.json { render json: @enquete.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /enquetes
  # POST /enquetes.json
  def create_default
    enquete = Enquete.new(
        name: "アンケート"
    )

    question_list = []
    type_h = {
      q_1: 'text',
      q_2: 'checkbox',
      q_3: 'radio',
      q_4: 'pulldown',
      q_5: 'textarea'
    }
    body_h = {
      q_1: '好きなスポーツを記入してください',
      q_2: 'よく飲むお酒を選択してください（複数回答可）',
      q_3: 'あなたの性別を選択してください',
      q_4: 'あなたの年齢を選択してください',
      q_5: 'このアンケートはどこでお知りになりましたか'
    }
    choice_h = {
      q_1: nil,
      q_2: %w(
        お酒は飲まない
        ビール
        日本酒
        焼酎
        赤ワイン
        白ワイン
        カクテル
        ウイスキー
      ),
      q_3: %w(男性 女性),
      q_4: %w(20～29歳 30～39歳 40～49歳 50～59歳 60歳以上),
      q_5: nil
    }
    require_h = {
      q_1: true,
      q_2: true,
      q_3: true,
      q_4: true,
      q_5: false
    }
    (1..5).each do |n|
      question_list << Question.new(
        question_number: "q_#{n}",
        body: body_h["q_#{n}".to_sym],
        type: type_h["q_#{n}".to_sym],
        choices: choice_h["q_#{n}".to_sym],
        required_column: require_h["q_#{n}".to_sym]
      )
    end

    enquete.questions = question_list
    enquete.save!

    render text: "completed"
  end

  # PUT /enquetes/1
  # PUT /enquetes/1.json
  def update
    @enquete = Enquete.find(params[:id])

    respond_to do |format|
      if @enquete.update_attributes(params[:enquete])
        format.html { redirect_to @enquete, notice: 'Enquete was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enquete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquetes/1
  # DELETE /enquetes/1.json
  def destroy
    @enquete = Enquete.find(params[:id])
    @enquete.destroy

    respond_to do |format|
      format.html { redirect_to enquetes_url }
      format.json { head :no_content }
    end
  end
end

mongodb_enquete/app/helpers/enquetes_helper.rb
module EnquetesHelper
end

mongodb_enquete/app/views/enquetes/_form.html.erb
<%= form_for(@enquete) do |f| %>
  <% if @enquete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enquete.errors.count, "error") %> prohibited this enquete from being saved:</h2>

      <ul>
      <% @enquete.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mongodb_enquete/app/views/enquetes/edit.html.erb
<h1>Editing enquete</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquete %> |
<%= link_to 'Back', enquetes_path %>

mongodb_enquete/app/views/enquetes/index.html.erb
<h1>Listing enquetes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enquetes.each do |enquete| %>
  <tr>
    <td><%= enquete.name %></td>
    <td><%= link_to 'Show', enquete %></td>
    <td><%= link_to 'Edit', edit_enquete_path(enquete) %></td>
    <td><%= link_to 'Destroy', enquete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Answer', new_answer_path(enquete_id: enquete) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enquete', new_enquete_path %>

mongodb_enquete/app/views/enquetes/new.html.erb
<h1>New enquete</h1>

<%= render 'form' %>

<%= link_to 'Back', enquetes_path %>

mongodb_enquete/app/views/enquetes/show.html.erb
<h2><%= link_to "アンケートサンプル", {action: 'index'}, {style: "text-decoration: none"} %></h2>

<p id="notice"><%= notice %></p>

<div class="enquete_title"><%= @enquete.name %></div>

<%= form_for(:answer, url: {action: 'create'}) do |f| %>
  <% @enquete.questions.sort{|a,b| a.question_number.split(/_/)[1].to_i <=> b.question_number.split(/_/)[1].to_i}.each do |q| %>
    <% n = q.question_number.split(/_/)[1].to_i %>
    <div class="header">質問<%= n %></div>
    <div class="question">
      <% if @err_msg && @err_msg[q.question_number] %>
        <span class="err_msg"><%= @err_msg[q.question_number] %></span>
      <% end %>
      <div class="title"><%= q.body %> <%= %Q!<span class="requires">※必須</span>! if q.required_column %></div>
      <% if q.type == 'text' %>
        <%= f.text_field q.question_number %>
      <% elsif q.type == 'radio' %>
        <% q.choices.each_with_index do |choice, i| %>
          <%= check_box_tag "answer[#{q.question_number}][]", i, false, id: "answer_#{q.question_number}_#{i}" %>
          <label for="answer_<%= q.question_number %>_<%= i %>"><%= choice %></label><br />
        <% end %>
      <% elsif q.type == 'checkbox' %>
        <% q.choices.each_with_index do |choice, i| %>
          <%= f.radio_button q.question_number, i %>
          <label for="answer_<%= q.question_number %>_<%= i %>"><%= choice %></label><br />
        <% end %>
      <% elsif q.type == 'pulldown' %>
        <%
          list = []
          q.choices.each_with_index do |choice, i|
            list << [choice, i]
          end
        %>
        <%= f.select q.question_number, list %>
      <% elsif q.type == 'textarea' %>
        <%= f.text_area q.question_number, size: '40x5' %>
      <% end %>
    </div>
    <div class="clear"></div>
  <% end %>
  <%= f.hidden_field :user_id, value: 1 %>
  <%= f.hidden_field :enquete_id, value: @enquete.id %>
  <div><%= f.submit 'この内容で送信する' %></div>
<% end %>

<%= link_to 'Edit', edit_enquete_path(@enquete) %> |
<%= link_to 'Back', enquetes_path %>